CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

CAPELLA_FORK_EPOCH: 2
CAPELLA_FORK_VERSION: 0x20000092

# Time parameters
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 5

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Eth1FollowDistance is the number of eth1.0 blocks to wait before considering a new deposit for voting. This only applies after the chain as been started.
ETH1_FOLLOW_DISTANCE: 10

# EpochsPerEth1VotingPeriod defines how often the merkle root of deposit receipts get updated in beacon node on per epoch basis.
EPOCHS_PER_ETH1_VOTING_PERIOD: 2

# ShardCommitteePeriod is the minimum amount of epochs a validator must participate before exiting. 
SHARD_COMMITTEE_PERIOD: 16 

# MinValidatorWithdrawabilityDelay is the shortest amount of time a validator has to wait to withdraw.
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 16
